string obj_name
string parent_frame
string guid
geometry_msgs/Vector3 translation
geometry_msgs/Quaternion rotation
string cad_data
string cad_data_collision
string parent_file_path
std_msgs/ColorRGBA apperance_color
---
bool success